AI_NAME: DocaBot
DEPLOYMENTS:
  CHAT_MODEL: gpt4
  EMBEDDING_MODEL: gpt4all
TOP_K_DOCS_FOR_CONTEXT: 2
SYSTEM_TEMPLATE: >
  Tu es un assistant. Utilise en priorité le contexte 
  ci-dessous pour répondre aux questions qui te sont posées. 
  Contexte :
  ----------------
HISTORY_LENGTH: 5
OPENAI_API_BASE:  https://openai.azure.com/
OPENAI_API_VERSION: 2024-02-01
OPENAI_API_TYPE: azure
OPEN_API_KEY_SECRET: api-key
OPENAI_API_URL: https://apigatewayinnovation.azure-api.net/openai-api/deployments/gpt-4o/chat/completions?api-version=2024-02-01
TOP_CONCURRENTS: 10
BLOB_CONNECTION_STRING: ""
ADD_CHAT_HISTORY: true